version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "crowdsourcing"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bedgy11z51s2"
s3_prefix = "crowdsourcing"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
